### ISSUE TITLE
Banking Protection

### ISSUE THREAD

**Issue by D3RFLO** [Yothri/vHackOS-API#3]
Can you add the Banking Protection App to the api?

**Comment by johmarjac** [comment]
Sorry for late answer, somehow my notifications were messed up.

What do you mean with Banking Protection App? What kind of feature do you need? :)

**Comment by D3RFLO** [comment]
I mean a function to Update the Banking Protection. That is the app which increase the time someone need to bruteforce you

**Comment by johmarjac** [comment]
This is part of StoreEndpoint.

Either use AddTask to add a single upgrade, or FillTask to fill your task list with the specified AppType.

```csharp
vhGame game = new vhGame();
game.SetCredentials(...);
            
game.AppStoreEndpoint.AddTask(AppType.BankingProtection);
game.AppStoreEndpoint.FillTasks(AppType.BankingProtection);
```

**Comment by D3RFLO** [comment]
Ok, my mistake 😄 But is there a function to get the current level of the banking protection?

**Comment by johmarjac** [comment]
Yes, also from the AppStoreEndpoint there is Update() function which is for every Endpoint.
This will return a StoreResponse and in there is an App Array:
https://github.com/Yothri/vHackOS-API/blob/master/src/vHackOS-API/Web/Model/StoreResponse.cs#L38

The App class provides then infos like Level. Allthough I just saw, Level is of type string which is stupid, but you can cast it to int. Even better make a PR and fix it :D
